// app/nuxt.config.ts
import { defineNuxtConfig } from 'nuxt/config'

const url = process.env.NUXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || ''
const key =
  process.env.NUXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  process.env.SUPABASE_KEY ||
  ''

if (!url || !key) {
  // This shows in CI logs but does not expose secrets
  // (We warn at build time instead of crashing at runtime.)
  // eslint-disable-next-line no-console
  console.warn('[nuxt-config] Missing Supabase envs at build time (URL or KEY).')
}

export default defineNuxtConfig({
  ssr: false,
  nitro: { preset: 'static' },

  app: {
    head: {
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Rajdhani:wght@500;700&display=swap' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
        { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
        { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' },
        { rel: 'manifest', href: '/site.webmanifest' },
      ],
    },
  },

  modules: [
    '@nuxtjs/supabase',
    '@pinia/nuxt',
  ],

  runtimeConfig: {
    public: {
      supabase: {
        url,
        key,
        redirect: false,
        useSsrCookies: false,
      },
    },
  },

  supabase: {
    url,
    key,
    redirect: false,
    useSsrCookies: false,
  },


  // Include Tailwind entry so CSS is generated by Vite
  css: ['~/assets/css/tailwind.css'],

  // Ensure PostCSS runs Tailwind + Autoprefixer during build
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },

  vite: {
    build: {
      sourcemap: true,
    },
  },
})

