name: SWA Deploy (jthe.monster)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NUXT_PUBLIC_SUPABASE_URL: ${{ secrets.NUXT_PUBLIC_SUPABASE_URL || secrets.SUPABASE_URL }}
      NUXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NUXT_PUBLIC_SUPABASE_ANON_KEY || secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install deps (include dev)
        working-directory: app
        env:
          # Make sure we don't omit dev deps accidentally
          NODE_ENV: ""
          NPM_CONFIG_PRODUCTION: "false"
          NPM_CONFIG_OMIT: ""
          NPM_CONFIG_FUND: "false"
          NPM_CONFIG_AUDIT: "false"
          NUXT_TELEMETRY_DISABLED: "1"
          # Supabase envs for generate-time
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NUXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NUXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          npm ci --include=dev --ignore-scripts

      - name: Verify pinia/nuxt module is present
        working-directory: app
        run: node -e "console.log(require.resolve('@pinia/nuxt'))"

      - name: Env guard
        working-directory: app
        run: node scripts/check-env.cjs

      - name: Build (Nuxt generate)
        working-directory: app
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NUXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NUXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          npx nuxt prepare
          npm run generate

      - name: Sanity check Nuxt build output
        run: |
          ls -la app/.output/public/_nuxt/builds/meta
          test -n "$(ls -1 app/.output/public/_nuxt/*.js | head -n1)"

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "app"
          output_location: ".output/public"
          skip_api_build: true
